"""Tests for marker detection and comment style resolution."""

import re

import pytest

from gitignoreline.markers import (
    C_BLOCK_COMMENT,
    DOUBLE_DASH,
    DOUBLE_SLASH,
    HASH,
    HTML_COMMENT,
    PERCENT,
    SEMICOLON,
    CommentStyle,
    get_comment_style,
)


class TestGetCommentStyle:
    """Verify extension-to-comment-style resolution."""

    @pytest.mark.parametrize(
        "filepath,expected",
        [
            ("main.py", HASH),
            ("script.sh", HASH),
            ("config.yaml", HASH),
            ("config.yml", HASH),
            ("settings.toml", HASH),
            ("Gemfile.rb", HASH),
            (".env", HASH),
            ("app.js", DOUBLE_SLASH),
            ("app.ts", DOUBLE_SLASH),
            ("component.tsx", DOUBLE_SLASH),
            ("component.jsx", DOUBLE_SLASH),
            ("main.c", DOUBLE_SLASH),
            ("main.cpp", DOUBLE_SLASH),
            ("Main.java", DOUBLE_SLASH),
            ("main.go", DOUBLE_SLASH),
            ("lib.rs", DOUBLE_SLASH),
            ("Program.cs", DOUBLE_SLASH),
            ("main.swift", DOUBLE_SLASH),
            ("main.kt", DOUBLE_SLASH),
            ("query.sql", DOUBLE_DASH),
            ("script.lua", DOUBLE_DASH),
            ("Module.hs", DOUBLE_DASH),
            ("paper.tex", PERCENT),
            ("code.m", PERCENT),
            ("module.erl", PERCENT),
            ("index.html", HTML_COMMENT),
            ("page.htm", HTML_COMMENT),
            ("data.xml", HTML_COMMENT),
            ("icon.svg", HTML_COMMENT),
            ("notes.md", HTML_COMMENT),
            ("style.css", C_BLOCK_COMMENT),
            ("style.scss", C_BLOCK_COMMENT),
            ("config.ini", SEMICOLON),
            ("boot.asm", SEMICOLON),
            ("core.clj", SEMICOLON),
        ],
    )
    def test_known_extensions(self, filepath: str, expected: CommentStyle) -> None:
        result = get_comment_style(filepath)
        assert result is not None
        assert result.prefix == expected.prefix
        assert result.suffix == expected.suffix

    def test_unknown_extension_returns_none(self) -> None:
        assert get_comment_style("data.bin") is None
        assert get_comment_style("archive.tar.gz") is None

    def test_filename_map(self) -> None:
        result = get_comment_style("Makefile")
        assert result is not None
        assert result.prefix == "#"

        result = get_comment_style("Dockerfile")
        assert result is not None
        assert result.prefix == "#"

    def test_overrides(self) -> None:
        overrides = {".custom": ("@@", "@@")}
        result = get_comment_style("file.custom", overrides=overrides)
        assert result is not None
        assert result.prefix == "@@"
        assert result.suffix == "@@"

    def test_override_takes_precedence(self) -> None:
        overrides = {".py": ("//", "")}
        result = get_comment_style("main.py", overrides=overrides)
        assert result is not None
        assert result.prefix == "//"

    def test_path_with_directories(self) -> None:
        result = get_comment_style("src/utils/helpers.py")
        assert result is not None
        assert result.prefix == "#"

    def test_case_insensitive_extension(self) -> None:
        result = get_comment_style("FILE.PY")
        assert result is not None
        assert result.prefix == "#"


class TestCommentStylePatterns:
    """Verify regex patterns generated by CommentStyle."""

    def test_hash_line_pattern(self) -> None:
        pat = HASH.line_pattern
        assert pat.match("API_KEY = 'secret'  # gitignore")
        assert pat.match("x = 1 # gitignore")
        assert pat.match('url = "http://example.com"  # gitignore')
        assert not pat.match("# this is a normal comment")
        assert not pat.match("x = 1  # gitignore something else")

    def test_hash_line_only_pattern(self) -> None:
        pat = HASH.line_only_pattern
        assert pat.match("# gitignore")
        assert pat.match("  # gitignore")
        assert pat.match("    # gitignore  ")
        assert not pat.match("x = 1  # gitignore")

    def test_hash_block_patterns(self) -> None:
        assert HASH.block_start_pattern.match("# gitignore-start")
        assert HASH.block_start_pattern.match("  # gitignore-start")
        assert not HASH.block_start_pattern.match("# gitignore-start extra")

        assert HASH.block_end_pattern.match("# gitignore-end")
        assert HASH.block_end_pattern.match("  # gitignore-end")

    def test_double_slash_patterns(self) -> None:
        pat = DOUBLE_SLASH.line_pattern
        assert pat.match('const key = "abc123"; // gitignore')
        assert pat.match("int x = 42; // gitignore")

        assert DOUBLE_SLASH.block_start_pattern.match("// gitignore-start")
        assert DOUBLE_SLASH.block_end_pattern.match("// gitignore-end")

    def test_html_comment_patterns(self) -> None:
        pat = HTML_COMMENT.line_pattern
        assert pat.match('<div class="secret"><!-- gitignore -->')
        assert pat.match("  <!-- gitignore -->")

        assert HTML_COMMENT.line_only_pattern.match("<!-- gitignore -->")
        assert HTML_COMMENT.block_start_pattern.match("<!-- gitignore-start -->")
        assert HTML_COMMENT.block_end_pattern.match("<!-- gitignore-end -->")

    def test_c_block_comment_patterns(self) -> None:
        pat = C_BLOCK_COMMENT.line_pattern
        assert pat.match("  color: red; /* gitignore */")
        assert C_BLOCK_COMMENT.block_start_pattern.match("/* gitignore-start */")
        assert C_BLOCK_COMMENT.block_end_pattern.match("/* gitignore-end */")

    def test_double_dash_patterns(self) -> None:
        pat = DOUBLE_DASH.line_pattern
        assert pat.match("SELECT * FROM secrets; -- gitignore")
        assert DOUBLE_DASH.block_start_pattern.match("-- gitignore-start")
        assert DOUBLE_DASH.block_end_pattern.match("-- gitignore-end")

    def test_percent_patterns(self) -> None:
        pat = PERCENT.line_pattern
        assert pat.match("\\newcommand{\\secret}{hidden} % gitignore")
        assert PERCENT.block_start_pattern.match("% gitignore-start")

    def test_semicolon_patterns(self) -> None:
        pat = SEMICOLON.line_pattern
        assert pat.match("password = hunter2 ; gitignore")
        assert SEMICOLON.block_start_pattern.match("; gitignore-start")
